---
title: "Codebook"
author: "Ugo Lancia"
date: "17 Jun 2015"
output: html_document
---

This dataset was generated by the run_analysis script, from the original UCI HAR Dataset (dowloaded and included in the directory).
The original dataset consists of data generated by experiments  carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist.
The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 
The sensor acceleration signal, which has gravitational and body motion components, was separated into body acceleration and gravity.
From each window, a vector of features was obtained by calculating variables from the time and frequency domains.
Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). 
Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 
XYZ' is used to denote 3-axial signals in the X, Y and Z directions.
From the original datasets a secondary dataset was obtained (see README for details).

Following are the specifications for each single variables:

"subject": nominal, the subject from which data were obtained, from 1 to 30

"label": nominal, each of the six activities each subjects was engaged in when the recordings were made (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)
        
"tBodyAcc-mean()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations along the orizontal axis

"tBodyAcc-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations along the vertical axis

"tBodyAcc-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations along the anteroposterior axis

"tGravityAcc-mean()-X": continuos, mean of means (each of ones for a certain time window) of gravitational component accelerations along the orizontal axis

"tGravityAcc-mean()-Y": continuos, mean of means (each of ones for a certain time window) of gravitational component accelerations along the vertical axis

"tGravityAcc-mean()-Z": continuos, mean of means (each of ones for a certain time window) of gravitational component accelerations along the anteroposterior axis

"tBodyAccJerk-mean()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks along the orizontal axis

"tBodyAccJerk-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks along the vertical axis

"tBodyAccJerk-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks along the anteroposterior axis

"tBodyGyro-mean()-X": continuos, mean of means (each of ones for a certain time window) of body angular velocity along the orizontal axis

"tBodyGyro-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body angular velocity along the vertical axis

"tBodyGyro-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body angular velocity along the anteroposterior axis

"tBodyGyroJerk-mean()-X": continuos, mean of means (each of ones for a certain time window) of body angular jerks along the orizontal axis

"tBodyGyroJerk-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body angular jerks along the vertical axis

"tBodyGyroJerk-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body angular jerks along the anteroposterior axis

"tBodyAccMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of body acceleration

"tGravityAccMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the gravitational components acceleration

"tBodyAccJerkMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body jerks acceleration

"tBodyGyroMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular velocity

"tBodyGyroJerkMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular jerks

"fBodyAcc-mean()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency along the orizontal axis

"fBodyAcc-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency along the vertical axis

"fBodyAcc-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency along the anteroposterior axis

"fBodyAcc-meanFreq()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency of frequencies along the orizontal axis

"fBodyAcc-meanFreq()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency of frequencies along the vertical axis

"fBodyAcc-meanFreq()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations frequency of frequencies along the anteroposterior axis

"fBodyAccJerk-mean()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency along the orizontal axis

"fBodyAccJerk-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency along the vertical axis

"fBodyAccJerk-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency along the anteroposterior axis

"fBodyAccJerk-meanFreq()-X": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency of frequencies along the orizontal axis

"fBodyAccJerk-meanFreq()-Y": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency of frequencies along the vertical axis

"fBodyAccJerk-meanFreq()-Z": continuos, mean of means (each of ones for a certain time window) of body accelerations jerks frequency of frequencies along the anteroposterior axis

"fBodyGyro-mean()-X": continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency along the orizontal axis

"fBodyGyro-mean()-Y": continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency along the vertical axis

"fBodyGyro-mean()-Z": continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency along the anteroposterior axis

"fBodyGyro-meanFreq()-X": continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency of frequencies along the orizontal axis

"fBodyGyro-meanFreq()-Y": continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency of frequencies along the vertical axis

"fBodyGyro-meanFreq()-Z" continuos, mean of means (each of ones for a certain time window) of body angular velocity frequency of frequencies along the anteroposterior axis

"fBodyAccMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of body acceleration frequency

"fBodyAccMag-meanFreq()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of body acceleration frequency of frequencies

"fBodyBodyAccJerkMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body jerks acceleration frequency

"fBodyBodyAccJerkMag-meanFreq()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body jerks acceleration frequency of frequencies

"fBodyBodyGyroMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular velocity frequency

"fBodyBodyGyroMag-meanFreq()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular velocity frequency of frequencies

"fBodyBodyGyroJerkMag-mean()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular jerks frequency

"fBodyBodyGyroJerkMag-meanFreq()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular jerks frequency of frequencies

"tBodyAcc-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations along the orizontal axis

"tBodyAcc-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations along the vertical axis

"tBodyAcc-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations along the anteroposterior axis

"tGravityAcc-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of gravitational component accelerations along the orizontal axis 
"tGravityAcc-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of gravitational component accelerations along the vertical axis

"tGravityAcc-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of gravitational component accelerations along the vertical axis

"tBodyAccJerk-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks along the orizontal axis

"tBodyAccJerk-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks along the vertical axis

"tBodyAccJerk-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks along the anteroposterior axis

"tBodyGyro-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the orizontal axis

"tBodyGyro-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the vertical axis

"tBodyGyro-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the anteroposterior axis

"tBodyGyroJerk-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body angular jerks along the orizontal axis

"tBodyGyroJerk-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body angular jerks along the vertical axis

"tBodyGyroJerk-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body angular jerks along the anteroposterior axis

"tBodyAccMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of body acceleration

"tGravityAccMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the gravitational components acceleration

"tBodyAccJerkMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body jerks acceleration

"tBodyGyroMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular velocity

"tBodyGyroJerkMag-std()": continuos, mean of means (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular jerks

"fBodyAcc-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations frequency along the orizontal axis

"fBodyAcc-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations frequency along the vertical axis

"fBodyAcc-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations frequency along the anteroposterior axis

"fBodyAccJerk-std()-X": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks frequency along the orizontal axis

"fBodyAccJerk-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks frequency along the vertical axis

"fBodyAccJerk-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body accelerations jerks frequency along the anteroposterior axis

"fBodyGyro-std()-X":continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the orizontal axis 

"fBodyGyro-std()-Y": continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the vertical axis 

"fBodyGyro-std()-Z": continuos, mean of standard deviations (each of ones for a certain time window) of body angular velocity along the anteroposterior axis 

"fBodyAccMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of body acceleration frequency

"fBodyBodyAccJerkMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body jerks acceleration frequency

"fBodyBodyGyroMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular velocity frequency

"fBodyBodyGyroJerkMag-std()": continuos, mean of standard deviations (each of ones for a certain time window) of the magnitude of the three-dimensional signals of the body angular jerks frequency


 



